-- Persistent request rate limits for edge functions
CREATE TABLE IF NOT EXISTS public.request_rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject TEXT NOT NULL CHECK (char_length(subject) <= 200),
  endpoint TEXT NOT NULL CHECK (char_length(endpoint) <= 120),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_request_rate_limits_lookup
  ON public.request_rate_limits (subject, endpoint, created_at DESC);

CREATE OR REPLACE FUNCTION public.check_request_rate_limit(
  p_subject TEXT,
  p_endpoint TEXT,
  p_window_seconds INT,
  p_max_requests INT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_request_count INT;
BEGIN
  IF p_subject IS NULL OR btrim(p_subject) = '' THEN
    RETURN FALSE;
  END IF;

  IF p_endpoint IS NULL OR btrim(p_endpoint) = '' THEN
    RETURN FALSE;
  END IF;

  IF p_window_seconds <= 0 OR p_max_requests <= 0 THEN
    RETURN FALSE;
  END IF;

  -- Keep table growth bounded with opportunistic cleanup.
  DELETE FROM public.request_rate_limits
  WHERE created_at < now() - INTERVAL '1 day';

  SELECT COUNT(*)
  INTO v_request_count
  FROM public.request_rate_limits
  WHERE subject = p_subject
    AND endpoint = p_endpoint
    AND created_at >= now() - make_interval(secs => p_window_seconds);

  IF v_request_count >= p_max_requests THEN
    RETURN FALSE;
  END IF;

  INSERT INTO public.request_rate_limits (subject, endpoint)
  VALUES (p_subject, p_endpoint);

  RETURN TRUE;
END;
$$;

REVOKE ALL ON FUNCTION public.check_request_rate_limit(TEXT, TEXT, INT, INT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_request_rate_limit(TEXT, TEXT, INT, INT) TO service_role;

-- Centralized error events for frontend + edge observability.
CREATE TABLE IF NOT EXISTS public.error_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL CHECK (char_length(source) <= 80),
  level TEXT NOT NULL DEFAULT 'error' CHECK (level IN ('error', 'warning', 'info')),
  message TEXT NOT NULL CHECK (char_length(message) <= 4000),
  stack TEXT,
  context JSONB NOT NULL DEFAULT '{}'::jsonb,
  user_id UUID,
  request_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_error_events_created_at
  ON public.error_events (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_error_events_source_created_at
  ON public.error_events (source, created_at DESC);

ALTER TABLE public.error_events ENABLE ROW LEVEL SECURITY;
